// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc1
// source: after_create_user_tx.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AfterCreateUserTxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEmail     string                 `protobuf:"bytes,1,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AfterCreateUserTxRequest) Reset() {
	*x = AfterCreateUserTxRequest{}
	mi := &file_after_create_user_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AfterCreateUserTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfterCreateUserTxRequest) ProtoMessage() {}

func (x *AfterCreateUserTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_after_create_user_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfterCreateUserTxRequest.ProtoReflect.Descriptor instead.
func (*AfterCreateUserTxRequest) Descriptor() ([]byte, []int) {
	return file_after_create_user_tx_proto_rawDescGZIP(), []int{0}
}

func (x *AfterCreateUserTxRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type AfterCreateUserTxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AfterCreateUserTxResponse) Reset() {
	*x = AfterCreateUserTxResponse{}
	mi := &file_after_create_user_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AfterCreateUserTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfterCreateUserTxResponse) ProtoMessage() {}

func (x *AfterCreateUserTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_after_create_user_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfterCreateUserTxResponse.ProtoReflect.Descriptor instead.
func (*AfterCreateUserTxResponse) Descriptor() ([]byte, []int) {
	return file_after_create_user_tx_proto_rawDescGZIP(), []int{1}
}

func (x *AfterCreateUserTxResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_after_create_user_tx_proto protoreflect.FileDescriptor

const file_after_create_user_tx_proto_rawDesc = "" +
	"\n" +
	"\x1aafter_create_user_tx.proto\x12\x02pb\"8\n" +
	"\x18AfterCreateUserTxRequest\x12\x1c\n" +
	"\tuserEmail\x18\x01 \x01(\tR\tuserEmail\"5\n" +
	"\x19AfterCreateUserTxResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB=Z;github.com/2landhnal/digital-preservation-shared-payload/pbb\x06proto3"

var (
	file_after_create_user_tx_proto_rawDescOnce sync.Once
	file_after_create_user_tx_proto_rawDescData []byte
)

func file_after_create_user_tx_proto_rawDescGZIP() []byte {
	file_after_create_user_tx_proto_rawDescOnce.Do(func() {
		file_after_create_user_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_after_create_user_tx_proto_rawDesc), len(file_after_create_user_tx_proto_rawDesc)))
	})
	return file_after_create_user_tx_proto_rawDescData
}

var file_after_create_user_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_after_create_user_tx_proto_goTypes = []any{
	(*AfterCreateUserTxRequest)(nil),  // 0: pb.AfterCreateUserTxRequest
	(*AfterCreateUserTxResponse)(nil), // 1: pb.AfterCreateUserTxResponse
}
var file_after_create_user_tx_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_after_create_user_tx_proto_init() }
func file_after_create_user_tx_proto_init() {
	if File_after_create_user_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_after_create_user_tx_proto_rawDesc), len(file_after_create_user_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_after_create_user_tx_proto_goTypes,
		DependencyIndexes: file_after_create_user_tx_proto_depIdxs,
		MessageInfos:      file_after_create_user_tx_proto_msgTypes,
	}.Build()
	File_after_create_user_tx_proto = out.File
	file_after_create_user_tx_proto_goTypes = nil
	file_after_create_user_tx_proto_depIdxs = nil
}
