// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc1
// source: collect_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_collect_service_proto protoreflect.FileDescriptor

const file_collect_service_proto_rawDesc = "" +
	"\n" +
	"\x15collect_service.proto\x12\x02pb\x1a\x10tmp_object.proto\x1a\x18viruss_scan_result.proto\x1a\x1dextract_metadata_result.proto2\xf9\x02\n" +
	"\x0eCollectService\x12J\n" +
	"\x0fUpdateTmpObject\x12\x1a.pb.UpdateTmpObjectRequest\x1a\x1b.pb.UpdateTmpObjectResponse\x12J\n" +
	"\x0fCreateTmpObject\x12\x1a.pb.CreateTmpObjectRequest\x1a\x1b.pb.CreateTmpObjectResponse\x12_\n" +
	"\x16CreateVirussScanResult\x12!.pb.CreateVirussScanResultRequest\x1a\".pb.CreateVirussScanResultResponse\x12n\n" +
	"\x1bCreateExtractMetadataResult\x12&.pb.CreateExtractMetadataResultRequest\x1a'.pb.CreateExtractMetadataResultResponseB=Z;github.com/2landhnal/digital-preservation-shared-payload/pbb\x06proto3"

var file_collect_service_proto_goTypes = []any{
	(*UpdateTmpObjectRequest)(nil),              // 0: pb.UpdateTmpObjectRequest
	(*CreateTmpObjectRequest)(nil),              // 1: pb.CreateTmpObjectRequest
	(*CreateVirussScanResultRequest)(nil),       // 2: pb.CreateVirussScanResultRequest
	(*CreateExtractMetadataResultRequest)(nil),  // 3: pb.CreateExtractMetadataResultRequest
	(*UpdateTmpObjectResponse)(nil),             // 4: pb.UpdateTmpObjectResponse
	(*CreateTmpObjectResponse)(nil),             // 5: pb.CreateTmpObjectResponse
	(*CreateVirussScanResultResponse)(nil),      // 6: pb.CreateVirussScanResultResponse
	(*CreateExtractMetadataResultResponse)(nil), // 7: pb.CreateExtractMetadataResultResponse
}
var file_collect_service_proto_depIdxs = []int32{
	0, // 0: pb.CollectService.UpdateTmpObject:input_type -> pb.UpdateTmpObjectRequest
	1, // 1: pb.CollectService.CreateTmpObject:input_type -> pb.CreateTmpObjectRequest
	2, // 2: pb.CollectService.CreateVirussScanResult:input_type -> pb.CreateVirussScanResultRequest
	3, // 3: pb.CollectService.CreateExtractMetadataResult:input_type -> pb.CreateExtractMetadataResultRequest
	4, // 4: pb.CollectService.UpdateTmpObject:output_type -> pb.UpdateTmpObjectResponse
	5, // 5: pb.CollectService.CreateTmpObject:output_type -> pb.CreateTmpObjectResponse
	6, // 6: pb.CollectService.CreateVirussScanResult:output_type -> pb.CreateVirussScanResultResponse
	7, // 7: pb.CollectService.CreateExtractMetadataResult:output_type -> pb.CreateExtractMetadataResultResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_collect_service_proto_init() }
func file_collect_service_proto_init() {
	if File_collect_service_proto != nil {
		return
	}
	file_tmp_object_proto_init()
	file_viruss_scan_result_proto_init()
	file_extract_metadata_result_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_collect_service_proto_rawDesc), len(file_collect_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_collect_service_proto_goTypes,
		DependencyIndexes: file_collect_service_proto_depIdxs,
	}.Build()
	File_collect_service_proto = out.File
	file_collect_service_proto_goTypes = nil
	file_collect_service_proto_depIdxs = nil
}
