// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc1
// source: core_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_core_service_proto protoreflect.FileDescriptor

const file_core_service_proto_rawDesc = "" +
	"\n" +
	"\x12core_service.proto\x12\x02pb\x1a\x11upload_file.proto\x1a\x1aafter_create_user_tx.proto2\x9c\x01\n" +
	"\vCoreService\x12;\n" +
	"\n" +
	"UploadFile\x12\x15.pb.UploadFileRequest\x1a\x16.pb.UploadFileResponse\x12P\n" +
	"\x11AfterCreateUserTx\x12\x1c.pb.AfterCreateUserTxRequest\x1a\x1d.pb.AfterCreateUserTxResponseB=Z;github.com/2landhnal/digital-preservation-shared-payload/pbb\x06proto3"

var file_core_service_proto_goTypes = []any{
	(*UploadFileRequest)(nil),         // 0: pb.UploadFileRequest
	(*AfterCreateUserTxRequest)(nil),  // 1: pb.AfterCreateUserTxRequest
	(*UploadFileResponse)(nil),        // 2: pb.UploadFileResponse
	(*AfterCreateUserTxResponse)(nil), // 3: pb.AfterCreateUserTxResponse
}
var file_core_service_proto_depIdxs = []int32{
	0, // 0: pb.CoreService.UploadFile:input_type -> pb.UploadFileRequest
	1, // 1: pb.CoreService.AfterCreateUserTx:input_type -> pb.AfterCreateUserTxRequest
	2, // 2: pb.CoreService.UploadFile:output_type -> pb.UploadFileResponse
	3, // 3: pb.CoreService.AfterCreateUserTx:output_type -> pb.AfterCreateUserTxResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_service_proto_init() }
func file_core_service_proto_init() {
	if File_core_service_proto != nil {
		return
	}
	file_upload_file_proto_init()
	file_after_create_user_tx_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_service_proto_rawDesc), len(file_core_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_service_proto_goTypes,
		DependencyIndexes: file_core_service_proto_depIdxs,
	}.Build()
	File_core_service_proto = out.File
	file_core_service_proto_goTypes = nil
	file_core_service_proto_depIdxs = nil
}
