// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc1
// source: get_presigned_url.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPresignedUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StorageId     string                 `protobuf:"bytes,1,opt,name=storageId,proto3" json:"storageId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedUrlRequest) Reset() {
	*x = GetPresignedUrlRequest{}
	mi := &file_get_presigned_url_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedUrlRequest) ProtoMessage() {}

func (x *GetPresignedUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_get_presigned_url_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedUrlRequest.ProtoReflect.Descriptor instead.
func (*GetPresignedUrlRequest) Descriptor() ([]byte, []int) {
	return file_get_presigned_url_proto_rawDescGZIP(), []int{0}
}

func (x *GetPresignedUrlRequest) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

type GetPresignedUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresignedUrlResponse) Reset() {
	*x = GetPresignedUrlResponse{}
	mi := &file_get_presigned_url_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresignedUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresignedUrlResponse) ProtoMessage() {}

func (x *GetPresignedUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_presigned_url_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresignedUrlResponse.ProtoReflect.Descriptor instead.
func (*GetPresignedUrlResponse) Descriptor() ([]byte, []int) {
	return file_get_presigned_url_proto_rawDescGZIP(), []int{1}
}

func (x *GetPresignedUrlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_get_presigned_url_proto protoreflect.FileDescriptor

const file_get_presigned_url_proto_rawDesc = "" +
	"\n" +
	"\x17get_presigned_url.proto\x12\x02pb\"6\n" +
	"\x16GetPresignedUrlRequest\x12\x1c\n" +
	"\tstorageId\x18\x01 \x01(\tR\tstorageId\"+\n" +
	"\x17GetPresignedUrlResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03urlB=Z;github.com/2landhnal/digital-preservation-shared-payload/pbb\x06proto3"

var (
	file_get_presigned_url_proto_rawDescOnce sync.Once
	file_get_presigned_url_proto_rawDescData []byte
)

func file_get_presigned_url_proto_rawDescGZIP() []byte {
	file_get_presigned_url_proto_rawDescOnce.Do(func() {
		file_get_presigned_url_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_get_presigned_url_proto_rawDesc), len(file_get_presigned_url_proto_rawDesc)))
	})
	return file_get_presigned_url_proto_rawDescData
}

var file_get_presigned_url_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_get_presigned_url_proto_goTypes = []any{
	(*GetPresignedUrlRequest)(nil),  // 0: pb.GetPresignedUrlRequest
	(*GetPresignedUrlResponse)(nil), // 1: pb.GetPresignedUrlResponse
}
var file_get_presigned_url_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_get_presigned_url_proto_init() }
func file_get_presigned_url_proto_init() {
	if File_get_presigned_url_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_get_presigned_url_proto_rawDesc), len(file_get_presigned_url_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_get_presigned_url_proto_goTypes,
		DependencyIndexes: file_get_presigned_url_proto_depIdxs,
		MessageInfos:      file_get_presigned_url_proto_msgTypes,
	}.Build()
	File_get_presigned_url_proto = out.File
	file_get_presigned_url_proto_goTypes = nil
	file_get_presigned_url_proto_depIdxs = nil
}
