// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc1
// source: get_file_format.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFileFormatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Extension     string                 `protobuf:"bytes,1,opt,name=extension,proto3" json:"extension,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileFormatRequest) Reset() {
	*x = GetFileFormatRequest{}
	mi := &file_get_file_format_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileFormatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileFormatRequest) ProtoMessage() {}

func (x *GetFileFormatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_get_file_format_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileFormatRequest.ProtoReflect.Descriptor instead.
func (*GetFileFormatRequest) Descriptor() ([]byte, []int) {
	return file_get_file_format_proto_rawDescGZIP(), []int{0}
}

func (x *GetFileFormatRequest) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *GetFileFormatRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetFileFormatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	IsStable      bool                   `protobuf:"varint,3,opt,name=isStable,proto3" json:"isStable,omitempty"`
	StablePoint   int32                  `protobuf:"varint,4,opt,name=stablePoint,proto3" json:"stablePoint,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileFormatResponse) Reset() {
	*x = GetFileFormatResponse{}
	mi := &file_get_file_format_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileFormatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileFormatResponse) ProtoMessage() {}

func (x *GetFileFormatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_file_format_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileFormatResponse.ProtoReflect.Descriptor instead.
func (*GetFileFormatResponse) Descriptor() ([]byte, []int) {
	return file_get_file_format_proto_rawDescGZIP(), []int{1}
}

func (x *GetFileFormatResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetFileFormatResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetFileFormatResponse) GetIsStable() bool {
	if x != nil {
		return x.IsStable
	}
	return false
}

func (x *GetFileFormatResponse) GetStablePoint() int32 {
	if x != nil {
		return x.StablePoint
	}
	return 0
}

func (x *GetFileFormatResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetFileFormatResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_get_file_format_proto protoreflect.FileDescriptor

const file_get_file_format_proto_rawDesc = "" +
	"\n" +
	"\x15get_file_format.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"N\n" +
	"\x14GetFileFormatRequest\x12\x1c\n" +
	"\textension\x18\x01 \x01(\tR\textension\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xf7\x01\n" +
	"\x15GetFileFormatResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bisStable\x18\x03 \x01(\bR\bisStable\x12 \n" +
	"\vstablePoint\x18\x04 \x01(\x05R\vstablePoint\x128\n" +
	"\tcreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB6Z4github.com/2landhnal/preservelab-migrate/internal/pbb\x06proto3"

var (
	file_get_file_format_proto_rawDescOnce sync.Once
	file_get_file_format_proto_rawDescData []byte
)

func file_get_file_format_proto_rawDescGZIP() []byte {
	file_get_file_format_proto_rawDescOnce.Do(func() {
		file_get_file_format_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_get_file_format_proto_rawDesc), len(file_get_file_format_proto_rawDesc)))
	})
	return file_get_file_format_proto_rawDescData
}

var file_get_file_format_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_get_file_format_proto_goTypes = []any{
	(*GetFileFormatRequest)(nil),  // 0: pb.GetFileFormatRequest
	(*GetFileFormatResponse)(nil), // 1: pb.GetFileFormatResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_get_file_format_proto_depIdxs = []int32{
	2, // 0: pb.GetFileFormatResponse.createdAt:type_name -> google.protobuf.Timestamp
	2, // 1: pb.GetFileFormatResponse.updatedAt:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_get_file_format_proto_init() }
func file_get_file_format_proto_init() {
	if File_get_file_format_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_get_file_format_proto_rawDesc), len(file_get_file_format_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_get_file_format_proto_goTypes,
		DependencyIndexes: file_get_file_format_proto_depIdxs,
		MessageInfos:      file_get_file_format_proto_msgTypes,
	}.Build()
	File_get_file_format_proto = out.File
	file_get_file_format_proto_goTypes = nil
	file_get_file_format_proto_depIdxs = nil
}
