// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc1
// source: migrate_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_migrate_service_proto protoreflect.FileDescriptor

const file_migrate_service_proto_rawDesc = "" +
	"\n" +
	"\x15migrate_service.proto\x12\x02pb\x1a\x15get_file_format.proto\x1a\x18is_file_acceptable.proto2\xc0\x01\n" +
	"\x0eMigrateService\x12D\n" +
	"\rGetFileFormat\x12\x18.pb.GetFileFormatRequest\x1a\x19.pb.GetFileFormatResponse\x12h\n" +
	"\x19CheckFileFormatAcceptable\x12$.pb.CheckFileFormatAcceptableRequest\x1a%.pb.CheckFileFormatAcceptableResponseB=Z;github.com/2landhnal/digital-preservation-shared-payload/pbb\x06proto3"

var file_migrate_service_proto_goTypes = []any{
	(*GetFileFormatRequest)(nil),              // 0: pb.GetFileFormatRequest
	(*CheckFileFormatAcceptableRequest)(nil),  // 1: pb.CheckFileFormatAcceptableRequest
	(*GetFileFormatResponse)(nil),             // 2: pb.GetFileFormatResponse
	(*CheckFileFormatAcceptableResponse)(nil), // 3: pb.CheckFileFormatAcceptableResponse
}
var file_migrate_service_proto_depIdxs = []int32{
	0, // 0: pb.MigrateService.GetFileFormat:input_type -> pb.GetFileFormatRequest
	1, // 1: pb.MigrateService.CheckFileFormatAcceptable:input_type -> pb.CheckFileFormatAcceptableRequest
	2, // 2: pb.MigrateService.GetFileFormat:output_type -> pb.GetFileFormatResponse
	3, // 3: pb.MigrateService.CheckFileFormatAcceptable:output_type -> pb.CheckFileFormatAcceptableResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_migrate_service_proto_init() }
func file_migrate_service_proto_init() {
	if File_migrate_service_proto != nil {
		return
	}
	file_get_file_format_proto_init()
	file_is_file_acceptable_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_migrate_service_proto_rawDesc), len(file_migrate_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_migrate_service_proto_goTypes,
		DependencyIndexes: file_migrate_service_proto_depIdxs,
	}.Build()
	File_migrate_service_proto = out.File
	file_migrate_service_proto_goTypes = nil
	file_migrate_service_proto_depIdxs = nil
}
