// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc1
// source: upload_file.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserEmail     string                 `protobuf:"bytes,1,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	OriginalName  string                 `protobuf:"bytes,2,opt,name=originalName,proto3" json:"originalName,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	FormatVersion string                 `protobuf:"bytes,5,opt,name=formatVersion,proto3" json:"formatVersion,omitempty"`
	Storage       string                 `protobuf:"bytes,6,opt,name=storage,proto3" json:"storage,omitempty"`
	StorageID     string                 `protobuf:"bytes,7,opt,name=storageID,proto3" json:"storageID,omitempty"`
	VerifyKey     []byte                 `protobuf:"bytes,8,opt,name=verifyKey,proto3" json:"verifyKey,omitempty"`
	Signature     []byte                 `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	SignAlg       string                 `protobuf:"bytes,10,opt,name=signAlg,proto3" json:"signAlg,omitempty"`
	FolderID      int64                  `protobuf:"varint,11,opt,name=folderID,proto3" json:"folderID,omitempty"`
	Name          string                 `protobuf:"bytes,12,opt,name=name,proto3" json:"name,omitempty"`
	Category      string                 `protobuf:"bytes,13,opt,name=category,proto3" json:"category,omitempty"`
	Version       int32                  `protobuf:"varint,14,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_upload_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upload_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_upload_file_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *UploadFileRequest) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *UploadFileRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *UploadFileRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *UploadFileRequest) GetFormatVersion() string {
	if x != nil {
		return x.FormatVersion
	}
	return ""
}

func (x *UploadFileRequest) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *UploadFileRequest) GetStorageID() string {
	if x != nil {
		return x.StorageID
	}
	return ""
}

func (x *UploadFileRequest) GetVerifyKey() []byte {
	if x != nil {
		return x.VerifyKey
	}
	return nil
}

func (x *UploadFileRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *UploadFileRequest) GetSignAlg() string {
	if x != nil {
		return x.SignAlg
	}
	return ""
}

func (x *UploadFileRequest) GetFolderID() int64 {
	if x != nil {
		return x.FolderID
	}
	return 0
}

func (x *UploadFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadFileRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UploadFileRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_upload_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upload_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_upload_file_proto_rawDescGZIP(), []int{1}
}

func (x *UploadFileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_upload_file_proto protoreflect.FileDescriptor

const file_upload_file_proto_rawDesc = "" +
	"\n" +
	"\x11upload_file.proto\x12\x02pb\"\x9b\x03\n" +
	"\x11UploadFileRequest\x12\x1c\n" +
	"\tuserEmail\x18\x01 \x01(\tR\tuserEmail\x12\"\n" +
	"\foriginalName\x18\x02 \x01(\tR\foriginalName\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12$\n" +
	"\rformatVersion\x18\x05 \x01(\tR\rformatVersion\x12\x18\n" +
	"\astorage\x18\x06 \x01(\tR\astorage\x12\x1c\n" +
	"\tstorageID\x18\a \x01(\tR\tstorageID\x12\x1c\n" +
	"\tverifyKey\x18\b \x01(\fR\tverifyKey\x12\x1c\n" +
	"\tsignature\x18\t \x01(\fR\tsignature\x12\x18\n" +
	"\asignAlg\x18\n" +
	" \x01(\tR\asignAlg\x12\x1a\n" +
	"\bfolderID\x18\v \x01(\x03R\bfolderID\x12\x12\n" +
	"\x04name\x18\f \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\r \x01(\tR\bcategory\x12\x18\n" +
	"\aversion\x18\x0e \x01(\x05R\aversion\".\n" +
	"\x12UploadFileResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB=Z;github.com/2landhnal/digital-preservation-shared-payload/pbb\x06proto3"

var (
	file_upload_file_proto_rawDescOnce sync.Once
	file_upload_file_proto_rawDescData []byte
)

func file_upload_file_proto_rawDescGZIP() []byte {
	file_upload_file_proto_rawDescOnce.Do(func() {
		file_upload_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_upload_file_proto_rawDesc), len(file_upload_file_proto_rawDesc)))
	})
	return file_upload_file_proto_rawDescData
}

var file_upload_file_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_upload_file_proto_goTypes = []any{
	(*UploadFileRequest)(nil),  // 0: pb.UploadFileRequest
	(*UploadFileResponse)(nil), // 1: pb.UploadFileResponse
}
var file_upload_file_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_upload_file_proto_init() }
func file_upload_file_proto_init() {
	if File_upload_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_upload_file_proto_rawDesc), len(file_upload_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_upload_file_proto_goTypes,
		DependencyIndexes: file_upload_file_proto_depIdxs,
		MessageInfos:      file_upload_file_proto_msgTypes,
	}.Build()
	File_upload_file_proto = out.File
	file_upload_file_proto_goTypes = nil
	file_upload_file_proto_depIdxs = nil
}
